language: go

sudo: false

matrix:
  include:
    - go: "1.10.x"
      script: go test -v --race ./...
    - go: "1.11.x"
      script: go test -v --race -mod=vendor ./...
    - go: "1.12.x"
      script: go test -v --race -mod=vendor ./...

install: true

env:
  - GO111MODULE=on
